modLoader = "javafml" #mandatory`
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL = "${mod_issue_tracker}" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "${mod_display_url}" #optional
logoFile = "${mod_logo_file}" #optional
credits = "${mod_credits}" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config = "irons_spellbooks.mixins.json"
[[accessTransformers]]
## The file is relative to the output directory of the resources, or the root path inside the jar when compiled
## The 'resources' directory represents the root output directory of the resources
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
# the modid of the dependency
modId="neoforge" #mandatory
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type="required" #mandatory
# Optional field describing why the dependency is required or why it is incompatible
# reason="..."
# The version range of the dependency
versionRange="${neo_version_range}" #mandatory
# An ordering relationship for the dependency.
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="caelus"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${caelus_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${geckolib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playeranimator"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${player_animator_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playeranimator"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[${player_animator_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[9.0.5+1.21.0,)"
ordering="NONE"
side="BOTH"