
name: 💡 Feature request
description: Suggest new functionality, new content or balancing changes
labels: [feature request]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to improve
    validations:
      required: true
  - type: textarea
    id: experience
    attributes:
      label: How it improves the player experience/Developer experience
      description: Describe how this would make the game more fun, deep, intuitive, interesting or immersive
    validations:
      required: true
